# Generated by Django 3.2.16 on 2022-12-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
